title: Vangelis Chocholis
logo: ./assets/img/linkedIn_image.jpg
description: #>
 # [LinkedIn](https://www.linkedin.com/in/your-linkedin-profile) |
 # [Email](mailto:your.email@example.com)
#show_downloads: true
theme: jekyll-theme-minimal

author:
 email: vangelischocholis@gmail.com
 github: Vangelis-Chocholis
 linkedin: vangelis-chocholis
