title: Vangelis Chocholis
logo: ./assets/img/linkedIn_image.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal


email: vangelischocholis@gmail.com
  
  # Social links
github: Vangelis-Chocholis
#linkedin: vangelis-chocholis
