title: Vangelis Chocholis
logo: ./assets/img/linkedIn_image.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal


email: vangelischocholis@gmail.com

# Social links
github: https://github.com/Vangelis-Chocholis
linkedin: https://www.linkedin.com/in/vangelis-chocholis/
