title: Vangelis Chocholis
logo: ./assets/img/linkedIn_image.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <a href="https://www.linkedin.com/in/vangelis-chocholis/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  
 # <a href="vangelischocholis@gmail.com"> <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white"> </a>

theme: jekyll-theme-minimal
