title: Vangelis Chocholis
logo: ./assets/img/linkedIn_image.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal

author:
  email: vangelischocholis@gmail.com
  github: Vangelis-Chocholis
  linkedin: vangelis-chocholis
