title: Vangelis Chocholis
logo: ./assets/img/linkedIn_image.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist with a strong quantitative background,
  proficient in delivering end-to-end solutions, including data extraction,
  data visualization, statistical analysis and machine learning. <br><br>
  
  <a href="https://www.linkedin.com/in/vangelis-chocholis/"> <img src="https://img.shields.io/badge/LinkedIn-0A66C2.svg?style=for-the-badge&logo=LinkedIn&logoColor=white"> </a> 
  
 # <a href="vangelischocholis@gmail.com"> <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white"> </a>

theme: jekyll-theme-minimal
